### ISSUE TITLE
Small plots on Mac  with spen = 'oglpen'

### ISSUE THREAD

**Issue by maxvelasques** [ahay/src#166]
Hi,
I just updated my system to macOS Catalina, and I'm getting a different behavior when I plot things (compared to macOS Mojave).

For example, if I type: sfspike nsp=1 n1=4000 d1=0.0005 k1=200 | sfgraph | sfpen

I get the right plot, but only covering 1/4 of the window (see image below).

<img width="1125" alt="01-small" src="https://user-images.githubusercontent.com/55670610/68078718-d2d13a00-fda1-11e9-8265-0c96b83d490c.png">

If I resize (just a little bit) the window, the plot covers the entire window (previous behavior).

<img width="1131" alt="02-big" src="https://user-images.githubusercontent.com/55670610/68078719-d369d080-fda1-11e9-990e-b76643270064.png">

Regards,

**Comment by maxvelasques** [comment]
I found a workaround that fixes the problem (at least for me):

In the file "oglpen.c" I removed the line:    glutInitWindowSize (win_width, win_height);

And added the line:     glutReshapeWindow(win_width,win_height);
after the call:   glutReshapeFunc (oglreshape); 

Now the plot covers the entire screen.

**Comment by zhichenggeng** [comment]
@maxvelasques Glad to see you have resolved this problem! 
According to https://developer.apple.com/macos/whats-new/, Apple has already deprecated OpenGL since macOS 10.15 and started to use [Metal](https://developer.apple.com/metal/).
This is why some functions of oglpen don't work well on Mac. We will try to solve this problem by implementing a new pen specifically for macOS or implement a new platform-independent pen. 
Please let me know if you have any suggestions or comments.
