### ISSUE TITLE
[BUG] Error while runing "make"

### ISSUE THREAD

**Issue by RosendOcana** [ahay/src#201]
:bug:  Bug report

**Description of the bug**

Hi, I was trying to install Madagascar on Ubuntu 20.04 LTS and get an error related to:

 Macoustic1D_FWI_ptb.c:(.text.startup+0x581): undefined reference to `sgesv_'

**Will attach the config and make logs:**

[logmake.txt](https://github.com/ahay/src/files/4704032/logmake.txt)
[log.txt](https://github.com/ahay/src/files/4704033/log.txt)

I have Anaconda installed, as I always use Devito, Pysit and other packages, alredy have the most of dependencies that Madagascar ask for. I just run 

**./configure --prefix=/path (It goes well)**
**make (and here comes the trouble)**

**Comment by jmonsegny** [comment]
The linker is not able to find the function sgesv_ which is from the Lapack library. Your configuration setup does not find this library, so it should refrain from compiling and linking any file calling Lapack. However, it does not refrain in this case because the SConstruct at users/carrot/ does not have the feature that prevents compilation when Lapack is not in the system.

You could try to correct the SConstruct by adding the conditional compilation structure for Lapack or simply install Lapack before installing Madagascar. In your system this is something like:

sudo apt-get install liblapack-dev

**Comment by zhichenggeng** [comment]
Fixed in 6ba3873.
